name: Golden Ruby Games
pygments: true

# for github pages
baseurl: /goldenrubygames

# for prose
prose:
  siteurl: "http://billybrown.github.io/goldenrubygames/"
  media: "/img"
  relativeLinks: "ABSOLUTE-URL.jsonp"